version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8099:80"
    depends_on:
      - db
    command: apt-get update
    command: apt-get install sudo
    command: apt-get install nano

  db:
    image: postgres:13
    volumes:
      - dbdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb

volumes:
  dbdata:
